# Generated by Django 4.2.5 on 2023-10-25 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 19, 19, 51, 918281, tzinfo=datetime.timezone.utc)),
        ),
    ]
