# Generated by Django 4.2.5 on 2023-10-19 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 21, 47, 52, 366624, tzinfo=datetime.timezone.utc)),
        ),
    ]
