# Generated by Django 4.2.4 on 2023-10-19 01:06

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_sniffrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 10, 19, 1, 6, 38, 54316))),
                ('num_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='dawghouseuser',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
