# Generated by Django 4.2.5 on 2023-10-25 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_bark_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 25, 18, 57, 42, 329111, tzinfo=datetime.timezone.utc)),
        ),
    ]
