# Generated by Django 4.2.4 on 2023-10-30 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_bark_num_howls_bark_num_yips_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bark',
            name='original_bark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.bark'),
        ),
    ]
