# Generated by Django 4.2.5 on 2023-10-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_bark_num_howls_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='num_yips',
            field=models.IntegerField(default=0),
        ),
    ]
