# Generated by Django 4.2.4 on 2023-10-19 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_bark_dawghouseuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 1, 16, 19, 25214, tzinfo=datetime.timezone.utc)),
        ),
    ]
