# Generated by Django 4.2.7 on 2023-11-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_bark_is_repost_bark_original_bark'),
    ]

    operations = [
        migrations.AddField(
            model_name='dawghouseuser',
            name='profile_picture',
            field=models.CharField(default='images/profilePicture.jpg', max_length=100),
        ),
    ]
