# Generated by Django 4.2.5 on 2023-10-23 01:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_bark_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='treated_by',
            field=models.ManyToManyField(blank=True, related_name='treats_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 1, 27, 34, 841813, tzinfo=datetime.timezone.utc)),
        ),
    ]
