# Generated by Django 4.2.5 on 2023-10-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_bark_treated_by_alter_bark_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 17, 0, 6, 726300, tzinfo=datetime.timezone.utc)),
        ),
    ]
