# Generated by Django 4.2.5 on 2023-10-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_bark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bark',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
