# Generated by Django 4.2.5 on 2023-10-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_created_at_bark_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='homepage.profile'),
        ),
    ]
