# Generated by Django 4.2.5 on 2023-10-11 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='bark',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bark',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bark',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
