# Generated by Django 4.2.5 on 2023-10-11 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_bark_num_likes_alter_bark_id_alter_bark_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
